version: '3.8'

services:
  app:
    build: .
    container_name: housing_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/housing_tracker

  db:
    image: postgres:15
    container_name: housing_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: housing_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: